import React from 'react'
import Card from '../Card/Card'
import './Grid.css'
function Grid() {
 
  return (
    <div className='align'>
        <Card title={"Crop Harvesting Machine"} info={""} description={"A combine harvester is used for the processes of farming such as reaping, threshing, and winnowing. Combine Harvester is the best machine that is used to harvest all types of crops like barley, wheat, rye, oats, corn, and much more. To increase farming activities a combine harvester is a perfect option for you. Rs. 24.5 lakh to Rs. 28 lakh."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Crop+Harvesting+Machine.jfif"}/>
        <Card title={"Chain Saw"} info={""} description={"Chain saws are of great value and widely used in agricultural sites, and other areas were necessary. They are identified by their rotating teeth which are attached to a rotating chain on a guide bar. A cylinder engine with a battery pack or gasoline is essential to power the chainsaw. Chainsaws are portable, handheld machines that can be used for a variety of woodwork/metalwork. These versatile devices can cut any material, regardless of how large or thick it is. Chainsaw is a dangerous tool and must be used with precaution.Rs. 5000 to Rs. 25000."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Chain+Saw.jfif"}/>
        <Card title={"Mowers"} info={""} description={"A mower is a machine that mows i.e., cuts grass or other plants that grow on the ground. Usually, mowing is distinguished from reaping, which uses similar implements, but is the traditional term for harvesting grain crops. Choose from a push-behind mower, a riding mower, a zero-turn mower, a belly-mounted mower or a pull-behind mower for keeping up with the maintenance of your lawn or pastures. If you are making hay, you might want a sickle-bar mower, a drum mower, or a disc mower. For large areas, there are brush mowers, batwing mowers and flail mowers to consider for your collection of farm equipment.Rs. 15000 to Rs.25000."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Mowers.jfif"}/>
        <Card title={"2 & 4 Stroke Sprayer Pump"} info={""} description={"Agricultural sprayers used in agricultural work are available in 2 and 4 stroke spray pumps in the market. These have been launched in the market with some features. With this help, the farmer can easily spray insecticides on crops in his fields. Apart from this, they can also be used for the cleanliness of the environment Rs. 9,000 – Rs. 22,000."} imglink={"https://876878013835-ps43.s3.amazonaws.com/2+%26+4+Stroke+Sprayer+Pump.jfif"}/>
        <Card title={"Manure Spreader"} info={""} description={"Manure Spreader is a machine that is used for agriculture purposes. In agriculture purposes, its main work is to distribute manure in a field as in a form of fertilizer. It is not working on its own engine but it is towed behind a tractor. This machine of agriculture is not so expensive, it is available at an affordable price starts from Rs. 55,000* to Rs. 5.00 lakh*, so every farmer can buy it in an easy way. It may vary on its capacity, brand, product type and material. In the price range, this farming technology can be adjusted in the budget of every farmer because its rate is cheaper."} imglink={"https://876878013835-ps43.s3.amazonaws.com/2+%26+4+Stroke+Sprayer+Pump.jfif"}/>
        <Card title={"Rotary Tiller"} info={""} description={"A Rotary Tiller is an important farming machine to perform all the activities of agriculture and using this farmer can easily increase their farming activities is the simplest way. It has curved tines that are connected to a rotating shaft to dig the soil and make it ready for planting. This machine is economical in the budget so there is no possibility to don’t use this machine in farming.Rs. 45000 to Rs. 1.25 lakh."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Rotary+Tiller.jfif"}/>
        <Card title={"Cultivator"} info={""} description={"A cultivator is one of the most essential farming machines that are used for tillage activities. It is the oldest farming machine that has been used many of the years. It is used to stir or loosen the soil or either to eliminate weeds and to provide drainage. The cultivator is used by an attachment from a tractor or self-propelled.Rs. 19,000 to Rs. 80,000."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Cultivator.jfif"}/>
        <Card title={"Roto Seed Drill"} info={""} description={"Roto Seed Drill is one of the popular machines for farming that is made with the combination of  Rotary Tiller and Seed Drill. It is used in almost all over India for the purpose of sowing seeds of wheat, barley, grass seeding. This farming machine is easy to operate and also gives fewer maintenance expenses. It has an easy operating system of changing seed varieties with less wastage of seeds. Rs. 1.4 lakh to Rs. 1.37 lakh"} imglink={"https://876878013835-ps43.s3.amazonaws.com/Roto+Seed+Drill.jfif"}/>
        <Card title={"Trolley Pump"} info={""} description={"These are ideal to spray insecticides , pesticides , fungisides , herbisides etc , in fields to protect the crops from pest attack. These sprayers are used in agriculture , horticulture , plantations , gardens , nursery etc . Rs. 50000 to Rs. 75000"} imglink={"https://876878013835-ps43.s3.amazonaws.com/Trolley+Pump.jfif"}/>
        <Card title={"Tractor"} info={""} description={"Tractors are generally associated with farming as farmers use them alongside machinery to perform implements like ploughing, tilling, sowing, and harrowing. In addition, a tractor is used for pushing or pulling the machinery, thereby making the farming operations more convenient. Min Rs. 5 Lakh"} imglink={"https://876878013835-ps43.s3.amazonaws.com/Tractor.jfif"}/>
        <Card title={"Agri-Drones"} info={""} description={"Agri-drones can be used to spray chemicals as they have reservoirs, which can be filled with fertilizers and pesticides for spraying on crops in very little time, as compared to traditional methods. Thus, drone technology can usher in a new era for precision agriculture."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Agri-Drones.jfif"}/>
        <Card title={"Solar System"} info={""} description={"The typical examples of direct use of solar energy like greenhouses or tunnel farming for cultivation of crops and vegetables and use of solar dryers for drying agricultural products have been comprehensively discussed. Similarly, the solar powered tubewells, tractors, and lights, etc. Rs. 20000 per piece"} imglink={"https://876878013835-ps43.s3.amazonaws.com/Solar+System.jfif"}/>
        <Card title={"Dielectric Soil Moisture Sensors"} info={""} description={"Dielectric Soil Moisture Sensors. Dielectric soil moisture sensors determine the soil moisture by measuring the dielectric constant of the soil, an electrical property that is highly dependent on the moisture content. The constant for a dry soil is between 3 and 5; about one for air; and is about 80 for water."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Dielectric+Soil+Moisture+Sensors.jfif"}/>
        <Card title={"Airflow Sensors"} info={""} description={"Airflow Sensors measure soil air permeability. Measurements can be made at singular locations or dynamically while in motion. The desired output is the pressure required to push a predetermined amount of air into the ground at a prescribed depth."} imglink={"https://876878013835-ps43.s3.amazonaws.com/Airflow+Sensors.jfif"}/>
        {/* <Card title={""} description={""} imglink={""}/> */}
    </div>
  )
}

export default Grid
